Feat/ver reports
TreinaDev/td11-portfoliorrr pull request #166
Opened 2024-02-09 15:26 UTC by Luckvc

## Alcançado com esse PR

Resolve a issue #160 

Criamos a tela de listagem denúncias pendentes, deferidas e indeferidas da plataforma. Acessível apenas para contas de administração. Acessada pelo dropdown menu.

E a tela de detalhes da denúncia, onde é exibido também o objeto reportado, sendo uma view geral e uma coluna com esse objeto sendo gerada com um `render partial`.

Na denúncia de perfil, aparecem os 3 últimos posts que tenham sido publicados em algum momento, mesmo que depois tenham sido arquivados. Futuramente aparecerão os posts removidos também.

Implementamos também alguns testes para validar que um usuário não consegue ver o botão de reportar no próprio conteúdo.

### Prints
- Listagem de denúncias
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/105655467/10c63c47-aa69-4d9f-b946-87d142abe954)

- Denúncia de publicação
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/105655467/c17c310f-737d-4969-85cb-025f239bf94e)

- Denúncia de perfil
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/105655467/26d21ec2-8bdf-4db6-b003-039c8b720795)

- Denúncia de comentário
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/105655467/ed07207a-5d26-4d92-98a4-580ec5ce8ac2)

2024-02-10 16:49 UTC, DanSmaR requested changes
@Luckvc e @rozbr96 , ficou muito boa essa feature 🥇 
Só duas observação abaixo para vcs verificarem.

2024-02-10 16:49 UTC, DanSmaR commented on spec/system/reports/admin_sees_reports_listing_page_spec.rb
> +    expect(current_path).to eq new_user_session_path
em algumas máquinas aqui do pessoal, de vez em quando acontece de esse tipo de teste falhar, pois, às vezes, não está dando tempo de mudar de url no teste. Para contornar isso, estamos utilizando o seguinte método.
```suggestion
    expect(page).to have_current_path new_user_session_path
```

2024-02-10 16:49 UTC, DanSmaR commented on spec/system/reports/admin_sees_report_spec.rb
> +    expect(page).to have_content "Criado por #{report.reportable.user.full_name}"
Pessoal, agora que eu percebi, nós estamos seguindo as práticas de teste que o João recomendou, de deixar o teste auto contido, ou seja, se estamos esperando uma mensagem de estar na tela, devemos declarar explicitamente no teste qual é essa mensagem. Os dados default do factory só seriam utilizados caso precisássemos criar uma instância de algo sem precisar fazer uma asserção sobre o conteúdo.

Todo nosso projeto está assim, e aí acaba quebrando o padrão nosso.

De mais, está muito bom o trabalho de vcs :)
```suggestion
    admin = create(:user, :admin)
    post = create(:post, :published)
    create(:report, :for_post)
    report = create(:report, reportable: post, message: 'Conteúdo pornográfico')
    create(:report, :for_comment)

    login_as admin
    visit reports_path
    page.all('.see_more').to_a.second.click

    expect(page).to have_current_path report_path(report)
    expect(page).to have_content report.reportable.title
    expect(page).to have_content 'Conteúdo pornográfico'
    expect(page).to have_content "Criado por #{report.reportable.user.full_name}"
```

2024-02-12 16:59 UTC, gmkoeb approved these changes
Muito bom, pessoal. Valeu por terem feito as traduções também ❤️.

2024-02-12 16:59 UTC, gmkoeb commented on spec/system/reports/user_report_spec.rb
> +    it 'e não vê botão de comentar no próprio perfil' do
Acho que aqui seria 'e não vê botão de denunciar no próprio perfil'

2024-02-12 17:50 UTC, Luckvc commented on spec/system/reports/user_report_spec.rb
> +    it 'e não vê botão de comentar no próprio perfil' do
Isso mesmo, obrigado!!

2024-02-12 17:51 UTC, anaresgalla approved these changes
Muito bom, meninos! 
Faria o mesmo comentário que o Danilo.
Vi o do Gabriel e aí me atentei para o detalhe tb
:)))

2024-02-12 18:55 UTC, DanSmaR approved these changes
Boa @Luckvc , ficou muito bom! 🥇

2024-02-12 19:04 UTC, merged