Mensagens de notificações
TreinaDev/td11-portfoliorrr pull request #174
Opened 2024-02-09 21:14 UTC by hreis1

Resolve #171 

Adiciona notificações
- novo comentário
- curtida em comentário
- curtida em post

Adiciona número de notificações no menu

![Captura de tela 2024-02-09 174208](https://github.com/TreinaDev/td11-portfoliorrr/assets/94029691/f4223492-0e8e-4d32-afad-32cd0ab8d237)

### Débitos
- marcar como lida ao clicar e mudar número no menu
- adicionar estilo para tela de notificações

2024-02-10 17:13 UTC, DanSmaR approved these changes
Aprovado! Bom trabalho 🥇

2024-02-11 18:09 UTC, DanSmaR requested changes
Segue mais uma recomendação interessante :)

2024-02-11 18:09 UTC, DanSmaR commented on app/views/notifications/_notifications.html.erb
> +          <p><%= link_to notification.notifiable.user.full_name, profile_path(notification.notifiable.user.profile) %> curtiu seu comentário
Para evitar esses if elses statements, e deixar o código com menos linhas, recomendo que use partials para renderizar cada mensagem dependendo do nome  da classe da instãncia do model. 

Para isso, crie partials para cada model, dando o nome da classe desse jeito: 
`_post.html.erb`
`_invitation.html.erb`,
`_comment.html.erb`
onde cada partial conterá o conteúdo que está em cada if aí em cima, Por exemplo, na partial `_post.html.erb`:
```erb
  <p><%= notification.notifiable.user.full_name %> fez uma <%= link_to 'publicação', post_path(notification.notifiable) %>
```

e nessa partial `_notification.html.erb`, vc chamaria uma partial apenas, onde o caminho seria dinâmico, dependendo do `notifiable` que está vindo de cada `notification`. Segue como ficaria:
```suggestion
  <div class="list-group">
     <%= render(
       partial: "notifications/#{notification.notifiable.class.name.downcase}" ,
       locals: { notification: notification }
     )%>            
   </div>
```

2024-02-12 01:10 UTC, paulohenrique-gh approved these changes
Muito bom, pessoal :)

2024-02-12 01:10 UTC, paulohenrique-gh commented on spec/system/notifications/user_sees_notifications_spec.rb
> +    expect(page.body.index('curtiu seu comentário')).to be > page.body.index('Você recebeu um convite')
Legal, não conhecia esses métodos ✌️

2024-02-12 01:10 UTC, paulohenrique-gh commented on app/views/notifications/_notifications.html.erb
> +          <p><%= link_to notification.notifiable.user.full_name, profile_path(notification.notifiable.user.profile) %> curtiu seu comentário
Muito boa a ideia @DanSmaR

2024-02-12 14:39 UTC, hreis1 commented on app/views/notifications/_notifications.html.erb
> +          <p><%= link_to notification.notifiable.user.full_name, profile_path(notification.notifiable.user.profile) %> curtiu seu comentário
boa Dan. Implementamos e ficou bem legal

2024-02-12 15:01 UTC, Luckvc requested changes

2024-02-12 17:29 UTC, hreis1 commented on spec/system/notifications/user_sees_new_follower_notification_spec.rb
> +    expect(page).to have_content 'começou a te seguir'
boa Lucas. Ajustamos

2024-02-12 17:31 UTC, hreis1 commented on app/views/notifications/_notifications.html.erb
> +          <p><%= link_to notification.notifiable.user.full_name, profile_path(notification.notifiable.user.profile) %> curtiu seu comentário
Verdade. Vamos refatorar

2024-02-12 17:43 UTC, Luckvc approved these changes

2024-02-12 17:43 UTC, merged