Fix/Data de publicação se torna obrigatoria para publicação programada
TreinaDev/td11-portfoliorrr pull request #178
Opened 2024-02-10 19:16 UTC by caiquedv

Essa PR resolve #176 

Antes não havia validação para data de publicação obrigatória em caso de agendamento gerando erros 

![Captura de tela 2024-02-10 151413](https://github.com/TreinaDev/td11-portfoliorrr/assets/101219858/99b6100f-7d5d-4da0-9820-ba3d476a7f11)

Essa PR corrige esse comportamento
![Captura de tela 2024-02-10 151559](https://github.com/TreinaDev/td11-portfoliorrr/assets/101219858/aaf0e9e7-d8f3-4fb0-a67a-bd72b896b995)

2024-02-10 20:57 UTC, anaresgalla approved these changes
tudo certinho aqui! ótimo trabalho! :) 🦆

2024-02-11 22:44 UTC, DanSmaR requested changes
Boa @caiquedv !

Só dá uma olhada num teste feito em outra PR de vcs, mas está dando falha aqui comigo

2024-02-11 22:44 UTC, DanSmaR commented on spec/system/posts/user_creates_post_spec.rb
>        expect(page).to have_content "Agendado para: #{I18n.l(posts.last.published_at.to_datetime, format: :long)}"
@caiquedv e @gmkoeb , eu fiz o pull da main atualizada, e essa linha ta falhando.
no controller não tem essa mensagem para aparecer, só a de cima.

2024-02-11 22:53 UTC, DanSmaR requested changes

2024-02-11 22:53 UTC, DanSmaR commented on spec/system/posts/user_creates_post_spec.rb
>        expect(page).to have_content "Agendado para: #{I18n.l(posts.last.published_at.to_datetime, format: :long)}"
no arquivo de teste `user_edits_post_spec.rb:158` tbm tá assim

2024-02-11 23:06 UTC, gmkoeb commented on spec/system/posts/user_creates_post_spec.rb
>        expect(page).to have_content "Agendado para: #{I18n.l(posts.last.published_at.to_datetime, format: :long)}"
Engraçado, se inverter o dia pelo mês no fill_in 'post_published_at', with: 2.days.from_now.strftime('%m/%d/%Y %H:%M') os testes passam. E pelo teste estar falhando só de noite eu acho deve ser algo de timezone que deixamos passar despercebido 😂

2024-02-11 23:08 UTC, DanSmaR commented on spec/system/posts/user_creates_post_spec.rb
>        expect(page).to have_content "Agendado para: #{I18n.l(posts.last.published_at.to_datetime, format: :long)}"
Boa

2024-02-11 23:11 UTC, DanSmaR commented on spec/system/posts/user_creates_post_spec.rb
>        expect(page).to have_content "Agendado para: #{I18n.l(posts.last.published_at.to_datetime, format: :long)}"
Aqui tbm tá quebrando na main

spec/system/posts/user_edits_post_spec.rb:159

```rb
expect(post_schedule_spy).to have_received(:perform_later).with(post)
```

2024-02-11 23:38 UTC, gmkoeb commented on spec/system/posts/user_creates_post_spec.rb
>        expect(page).to have_content "Agendado para: #{I18n.l(posts.last.published_at.to_datetime, format: :long)}"
Ahhh já entendi o bug. Por algum motivo quando passamos 2.days.from_now.strftime('%m/%d/%Y %H:%M'), o rails cria o post no banco de dados com o mês e o dia invertido, ou seja, ele acha que o mês é o dia e o dia é o mês. No caso 2 days from now cairia no mês 13, que não existe, e aí quebra os 2 testes. Se colocar 1.day.from_now ainda passa pq cai no mês 12 kkkkkk

2024-02-11 23:48 UTC, gmkoeb commented on spec/system/posts/user_creates_post_spec.rb
>        expect(page).to have_content "Agendado para: #{I18n.l(posts.last.published_at.to_datetime, format: :long)}"
Ou talvez o teste pode estar tentando preencher o formulário de data com o mês 13, não conseguindo e mandando o campo vazio. Aí o published_at chega nulo 🤔

2024-02-12 13:34 UTC, caiquedv commented on spec/system/posts/user_creates_post_spec.rb
>        expect(page).to have_content "Agendado para: #{I18n.l(posts.last.published_at.to_datetime, format: :long)}"
Corrigido @DanSmaR

2024-02-12 13:37 UTC, DanSmaR approved these changes

2024-02-12 13:42 UTC, merged