Refactor/melhora layout do perfil
TreinaDev/td11-portfoliorrr pull request #189
Opened 2024-02-12 20:10 UTC by gmkoeb

Essa PR aborda e resolve #184 

Melhoramos o layout da tela perfil. 

Prints:

![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/105087841/339ee46d-168e-4fd6-a06f-8387d9ded80d)

2024-02-13 03:56 UTC, DanSmaR requested changes
Ficou lindo demais, parabéns pelo empenho 🥇
Fiz algumas observações abaixo :)

2024-02-13 03:56 UTC, DanSmaR commented on app/views/profiles/_personal_info.html.erb
> +    <% end %>
Nesse trecho, para evitar repetição de código (a tag `li` e seu conteúdo), recomendo se atentar ao conceito DRY e aplicar o seguinte: 
```suggestion
    <% new_value = (value && attribute == 'birth_date') ? value.to_date : value  %>
    <li>
      <span class="fw-bold"><%= PersonalInfo.human_attribute_name(attribute) %></span>:
      <%= info_fixer(new_value) %>
    </li>
```

2024-02-13 03:56 UTC, DanSmaR commented on app/views/profiles/show.html.erb
> +        <%= link_to 'Alterar foto', edit_profile_path(@profile), class: 'badge bg-secondary mt-3' if current_user == @profile.user %>
Seria bom já adicionar a tradução de 'Alterar foto'. Dá uma sapeada para inserir tradução. O @Luckvc  começou uma nova PR para tradução, mas se já fizermos aqui, ganharíamos tempo :)

2024-02-13 03:56 UTC, DanSmaR commented on config/locales/professional_info.pt-BR.yml
> +    'false': 'Não Exibido no Perfil'
É necessário ter essa mesma tradução no arquivo `config/locales/personal_info.pt-BR.yml` ?
Só dúvida mesmo :)

2024-02-13 12:08 UTC, gmkoeb commented on app/views/profiles/_personal_info.html.erb
> +    <% end %>
Muito boa. Vou aplicar aqui

2024-02-13 12:44 UTC, gmkoeb commented on config/locales/professional_info.pt-BR.yml
> +    'false': 'Não Exibido no Perfil'
Não testei, mas creio que seja necessário, pq apesar de serem atributos iguais pertencem a models diferentes.

2024-02-13 13:24 UTC, GyodaiDDA requested changes
Cara, tá tudo ótimo, uma melhora significativa na apresentação da plataforma. Só comentei sobre um detalhe - que não é crítico de forma alguma e pode só ser uma questão de gosto pessoal, mas achei bom levantar a bola assim mesmo. o/

2024-02-13 13:24 UTC, GyodaiDDA commented on app/views/profiles/_profile_details.html.erb
![Screenshot_20240213_101917](https://github.com/TreinaDev/td11-portfoliorrr/assets/125773929/0b38341b-2efa-4fa8-bdbe-3c3ded488c76)
A única coisa que me incomodou foi que o texto aqui fica colado nas linhas que delimitam o card.

2024-02-13 13:34 UTC, gmkoeb commented on app/views/profiles/_profile_details.html.erb
É verdade. Arrumei aqui!

2024-02-14 00:47 UTC, paulohenrique-gh approved these changes
Pra mim parece tudo certo, pessoal. Bom trabalho ✌️

2024-02-14 02:02 UTC, GyodaiDDA approved these changes

2024-02-14 13:43 UTC, anaresgalla approved these changes
ficou mto bom, meninos! :)))

2024-02-14 14:08 UTC, DanSmaR approved these changes
Bom trabalho galera, valeu!

2024-02-14 14:08 UTC, merged