Feat/api endpoint recusa solicitação convite
TreinaDev/td11-portfoliorrr pull request #202
Opened 2024-02-13 18:42 UTC by eliseuramos93

2024-02-13 20:20 UTC, hreis1 approved these changes

2024-02-13 21:25 UTC, DanSmaR requested changes
Bom trabalho rapaziada ! 💯 
Somente um detalhe de auto contenção nos testes abaixo :)

2024-02-13 21:25 UTC, DanSmaR commented on spec/requests/apis/v1/invitation_requests/leader_denies_invitation_request_spec.rb
> +      expect(json_response['status']).to eq 'refused'
Pessoal, como aqui estamos seguindo princípio de testes auto-contidos, conforme orientação do João, temos de passar explicitamente o conteúdo que esperamos para cada atributo testado do objeto. No caso, na hora de criar o `invitation_request`, temos de passar o valor de cada atributo e fazer o expect desses valores.

2024-02-14 13:29 UTC, anaresgalla approved these changes
ótimo, meninos!

2024-02-14 13:42 UTC, eliseuramos93 commented on spec/requests/apis/v1/invitation_requests/leader_denies_invitation_request_spec.rb
> +      expect(json_response['status']).to eq 'refused'
Prontinho Dan, já ajustei aqui o teste :)

2024-02-14 13:56 UTC, DanSmaR commented on spec/requests/apis/v1/invitation_requests/leader_denies_invitation_request_spec.rb
> +      expect(json_response['status']).to eq 'refused'
Boa! :)

2024-02-14 13:57 UTC, DanSmaR approved these changes
Show de Bola :) 💯

2024-02-14 14:38 UTC, merged