Adiciona filtro de convites cancelados na listagem de convites
TreinaDev/td11-portfoliorrr pull request #204
Opened 2024-02-13 19:19 UTC by eliseuramos93

Esse PR aborda e resolve #196 

Na página de listagem de convites, os convites cancelados pelo Líder de Projeto apenas aparecem na aba "Todos", não aparecendo em nenhuma outra aba de filtro.

Convites cancelados são os que o líder de projeto envia inicialmente, e cancela antes de receber qualquer resposta por parte do usuário convidado do Portfoliorrr.

Esse PR adiciona o filtro que mostra os convites cancelados ao usuário.

2024-02-13 20:10 UTC, hreis1 approved these changes

2024-02-13 21:20 UTC, paulohenrique-gh approved these changes
Me parece tudo certo, pessoal. Bom trabalho!

2024-02-13 21:30 UTC, DanSmaR requested changes
Boa @eliseuramos93 e @GyodaiDDA , vcs estão fazendo grandes contribuições 🥇

2024-02-13 21:30 UTC, DanSmaR commented on spec/system/invitations/user_views_invitations_spec.rb
> +    expect(page).not_to have_content pending_invitation.project_title
Aqui os atributos devem estar explicítos conforme orientação do João sobre testes auto contidos :)

2024-02-14 13:25 UTC, anaresgalla approved these changes
bom trabalho, gente! :)))

2024-02-14 13:40 UTC, GyodaiDDA commented on spec/system/invitations/user_views_invitations_spec.rb
> +    expect(page).not_to have_content pending_invitation.project_title
Alteramos!

2024-02-14 13:58 UTC, DanSmaR commented on spec/system/invitations/user_views_invitations_spec.rb
> +    expect(page).not_to have_content pending_invitation.project_title
Show!

2024-02-14 13:59 UTC, DanSmaR approved these changes
Valeu demais 💯

2024-02-14 15:13 UTC, merged