Adiciona opção de assinatura e protege rotas pagas
TreinaDev/td11-portfoliorrr pull request #223
Opened 2024-02-14 22:39 UTC by Luckvc

## Alcançado com este PR

Resolve #210 
Resolve #211 

Adicionamos o modelo de assinaturas atrelada ao usuário, tendo o status de ativa ou não ativa. 

No caso de ativa, o usuário tem acesso às páginas de pesquisa de projetos e solicitação de convites.
No caso de inativa, ao entrar nessas páginas, o usuário vê uma mensagem dizendo que é só para assinantes, com um link para a tela de assinatura.

Quando uma assinatura é ativada, tem sua start_date atribuída automaticamente para o dia atual. E start_date nulificada quando a assinatura é desativada.

A tela de assinatura foi implementada e no momento um usuário pode apenas se tornar assinante, não consegue cancelar a inscrição. 

### Prints

- Tela bloqueada com a mensagem
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/105655467/80c39c01-fb49-4f3f-9ce2-6f9aec2bd537)
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/105655467/d294d755-108c-49bd-9313-f4bc4efd19e1)

- Tela de assinatura
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/105655467/851780fc-fe1a-4c85-8a6a-28d4cc7436d4)

- Navbar com destaque
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/105655467/be493cc6-e75a-4968-b54b-6bb466d46026)

2024-02-14 23:43 UTC, eliseuramos93 approved these changes
Parabéns pelo trabalho, galera! Sensacional conseguir fazer essa entrega nesse curto período de tempo!

Por mim, já estamos prontos para aprovação. Só coloquei alguns comentários aqui, que vocês podem considerar ou não :) boraaa

2024-02-14 23:43 UTC, eliseuramos93 commented on app/controllers/projects_controller.rb
> +    redirect_to root_path, alert: t('alerts.unauthorized')
Galera, essa linha ficou sem cobertura de testes. Só pra gente já ter isso mapeado.

2024-02-14 23:43 UTC, eliseuramos93 commented on spec/factories/subscriptions.rb
> +    status { 0 }
Entendi que esse comportamento é proposital, porque diretamente pelo `#activate!` essas infos já são preenchidas

2024-02-14 23:43 UTC, eliseuramos93 commented on config/routes.rb
> +  resources :subscriptions, only: %i[index show update]
Tentei acessar a rota de show e cheguei no seguinte resultado:

![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/111306649/3b989791-76a0-4567-a0d3-60ebf13a60ad)

2024-02-14 23:43 UTC, eliseuramos93 commented on app/views/shared/_navbar.html.erb
> +              <%= link_to Subscription.model_name.human, subscriptions_path(current_user.subscription), class: 'nav-link text-primary' %>
A rota index tá recebendo um parâmetro aqui, o id da assinatura, que não é necessário. Podemos remover aqui que funciona (testei no navegador)

2024-02-15 01:12 UTC, caiquedv approved these changes
Muito legal, galera! Parabéns!! 🍀

2024-02-15 03:01 UTC, DanSmaR requested changes
Ficou Sensacional, vcs são brabos demais!

Fiz algumas considerações abaixo :)

2024-02-15 11:40 UTC, Luckvc commented on app/controllers/projects_controller.rb
> +    redirect_to root_path, alert: t('alerts.unauthorized')
Vamos consertar! Obrigado!

2024-02-15 11:42 UTC, Luckvc commented on app/views/shared/_navbar.html.erb
> +              <%= link_to Subscription.model_name.human, subscriptions_path(current_user.subscription), class: 'nav-link text-primary' %>
Você está certo, isso ficou ai pois a ideia inicial era ser um show, quando mudamos, acabou ficando resquícios, vamos consertar!

2024-02-15 11:47 UTC, Luckvc commented on app/javascript/components/projects_vue.js
> +      freeUser: window.freeUser,
Faz total sentido, pensamos mais na exibição, vamos implementar!

2024-02-15 11:48 UTC, rozbr96 commented on config/routes.rb
> +  resources :subscriptions, only: %i[index show update]
Ops. Esse `show` não era para estar aí.

2024-02-15 13:15 UTC, merged