Conclui registro com informações adicionais
TreinaDev/td11-portfoliorrr pull request #34
Opened 2024-01-23 21:25 UTC by DanSmaR

Essa PR abrange e resolve #11

Usuário é encaminhado para a página de conclusão de cadasrto após clicar em criar conta, a fim de adicionar mais dados.

Usuário regular cadastra formação acadêmica

Usuário regular cadastra experiências profissionais

## User stories
### Redirecionamento automático
Como usuário recém-cadastrado, eu quero ser redirecionado para a página de preenchimento de informações adicionais para concluir meu perfil

### Cadastro de formação acadêmica
Como um usuário registrado na plataforma buscando oportunidades, quero poder adicionar minhas formações acadêmicas ao meu perfil profissional para mostrar minha qualificação formal à potenciais recrutadores

- [x] Cada formação acadêmica deve possuir o nome da instituição de ensino;
- [x] Cada formação acadêmica deve possuir o nome do curso;
- [x] Cada formação acadêmica deve ter uma data de início, com mês e ano;
- [x] Cada formação acadêmica pode ter uma data de término, com mês e ano, que pode ser estimada (futura);
- [x] Cada formação acadêmica deve ter uma opção de estar visível ou oculta;
- [ ] Cada formação acadêmica deve possuir um nível (superior, especialização, mestrado, doutorado, PhD, etc.);
- [ ] Cada formação acadêmica deve ter um status (cursando, concluída, trancada, desistência, etc.);

### Cadastro de experiências profissionais
Como um usuário registrado na plataforma buscando oportunidades, quero poder adicionar minhas experiências profissionais ao meu perfil profissional para me destacar aos recrutadores e conseguir projetos relevantes com meus objetivos de carreira

- [x] Cada experiência profissional deve ter o nome da empresa;
- [x]  Cada experiência profissional deve ter o nome do cargo exercido; 
- [x] Cada experiência profissional deve ter uma data de início; 
- [x] Cada experiência profissional pode ter uma data de término, se não for a experiência atual; 
- [x] Cada experiência profissional deve ter uma opção de estar visível ou oculta;
- [ ] Cada experiência profissional pode ser marcada como “atual” ou não; 
- [ ] Cada experiência profissional pode ter um resumo de 500 caracteres sobre as atividades exercidas nela;

2024-01-23 21:29 UTC, DanSmaR commented
@akaninja e @gabdemiranda, por gentileza, assim que possível, podem revisar o que já foi feito até o momento (marcado com checkbox acima).

2024-01-24 11:52 UTC, akaninja commented
> @akaninja e @gabdemiranda, por gentileza, assim que possível, podem revisar o que já foi feito até o momento (marcado com checkbox acima).

Tudo bem, pessoal? Vamos esperar vocês deixarem o PR direitinho antes de revisar, ok? Ainda estão faltando os prints das telas e, além disso, descrição do PR não precisa conter as funcionalidades que ainda não foram feitas, certo? Deixem na descrição do PR apenas o que o que ele entrega. E garantam que está feito tudo direitinho como a issue está pedindo, antes de pedir pra gente revisar. ;)

2024-01-24 13:40 UTC, DanSmaR commented
> > @akaninja e @gabdemiranda, por gentileza, assim que possível, podem revisar o que já foi feito até o momento (marcado com checkbox acima).
> 
> Tudo bem, pessoal? Vamos esperar vocês deixarem o PR direitinho antes de revisar, ok? Ainda estão faltando os prints das telas e, além disso, descrição do PR não precisa conter as funcionalidades que ainda não foram feitas, certo? Deixem na descrição do PR apenas o que o que ele entrega. E garantam que está feito tudo direitinho como a issue está pedindo, antes de pedir pra gente revisar. ;)

Boa! eh mesmo, valeu

2024-01-25 15:23 UTC, DanSmaR commented
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/58406436/8d97dfac-15c7-4fab-a8b5-18b36fecf61d)

![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/58406436/1af32d35-306d-4646-a8a7-65eabfaedd0f)

![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/58406436/c589e7a0-c50f-4411-84da-87a1a7efeea4)

![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/58406436/8e238cfa-fb1f-4762-a994-2e36d5eff7dd)

2024-01-25 20:19 UTC, akaninja requested changes
Senti falta de testes importantes, garantindo que um usuário não pode editar as informações de outros usuários. Além disso, tem testes com `x` e fica a dǘvida se deveriam estar no PR ou não.

Sugiro passar de novo pelo código todo, conferindo se está tudo completo mesmo. :)

2024-01-25 20:19 UTC, akaninja commented on spec/system/user_profile/user_edits_education_info_spec.rb
> +    xit 'com sucesso' do
Estes teste vão ficar assim sendo pulados? Se não fazem parte do conjunto de testes eles não deveriam estar aqui no PR.

Os testes não estão respeitando a estrutura AAA padrão.

2024-01-25 20:25 UTC, akaninja commented
Senti falta de testes importantes, garantindo que um usuário não pode editar as informações de outros usuários. Além disso, tem testes com `x` e fica a dǘvida se deveriam estar no PR ou não. Também percebi que tem testes fora da estrutura padrão AAA.

Sugiro passar de novo pelo código todo, conferindo se está tudo completo mesmo. :)

Eu fiz uma revisão exigindo mudanças, mas pra não travar vocês vou tirar isso e deixar o time de vcs revisar e aprovar depois. :)

2024-01-25 20:43 UTC, akaninja commented on spec/system/user_profile/user_edits_professional_info_spec.rb
> +      visit edit_professional_info_path(professional_info)
Poderia ter um teste garantindo que uma pessoa só pode acessar as próprias informações profissionais.

2024-01-26 01:12 UTC, DanSmaR commented on spec/system/user_profile/user_edits_education_info_spec.rb
> +    xit 'com sucesso' do
Voltamos com ele e refatoramos para levar em consideração as novas rotas para edição. Antes não havia um controller específico para esse model. Agora que tem, fizemos as modificações e tá rodando.

Com relação ao AAA, tiramos o expect() dali. É que não achamos outro ponto para testar a existência desse título do formulário de forma a evitar redundancia de testes.

2024-01-26 01:14 UTC, DanSmaR commented on spec/system/user_profile/user_edits_professional_info_spec.rb
> +      visit edit_professional_info_path(professional_info)
Feito o teste, bem lembrado :).

Fizemos testes de requests e de sistema

2024-01-26 01:20 UTC, DanSmaR commented on spec/system/visitor_sign_up_spec.rb
> +    it 'e pula a etapa de cadastro' do
Boa! Estranho mesmo. Correção feita :)

2024-01-26 01:22 UTC, DanSmaR commented
> Senti falta de testes importantes, garantindo que um usuário não pode editar as informações de outros usuários. Além disso, tem testes com `x` e fica a dǘvida se deveriam estar no PR ou não. Também percebi que tem testes fora da estrutura padrão AAA.
> 
> Sugiro passar de novo pelo código todo, conferindo se está tudo completo mesmo. :)
> 
> Eu fiz uma revisão exigindo mudanças, mas pra não travar vocês vou tirar isso e deixar o time de vcs revisar e aprovar depois. :)

Show de bola @akaninja, gratidão pela dedicação e pelas dicas dadas!

2024-01-26 12:42 UTC, GyodaiDDA commented on spec/system/user_profile/user_creates_professional_info_spec.rb
> +      fill_in 'Data de Saída', with: ''
Essa linha talvez não seja necessária?

2024-01-26 13:22 UTC, anaresgalla commented
@akaninja muito obrigada mesmo por todas as dicas, pela boa vontade, disponibilidade e ajuda de sempre!
 ;)

2024-01-26 14:12 UTC, GyodaiDDA requested changes
Apenas um pequeno acrescimo nos testes de sistema.

2024-01-26 14:12 UTC, GyodaiDDA commented on spec/system/user_profile/user_creates_professional_info_spec.rb
> +    it 'e os campos "Empresa", "Cargo" e "Data de Entrada" são obrigatórios' do
Falta um teste para certificar que a data de saída só não é obrigatória se current_job? == true.

2024-01-26 14:48 UTC, caiquedv approved these changes
Pessoal, como já revisaram as dicas do André e não ví mais nada a acrescentar, vou deixar aprovado. Dessa forma quando resolverem a conversa com o Gyodai, poderão fazer a merge.

2024-01-26 17:58 UTC, DanSmaR commented on spec/system/user_profile/user_creates_professional_info_spec.rb
> +    it 'e os campos "Empresa", "Cargo" e "Data de Entrada" são obrigatórios' do
Boa, Resolvido!

2024-01-26 18:10 UTC, gmkoeb approved these changes
Perfeito. Só achei que ficou faltando alguns helpers no show do profile, para caso o usuário não tenha cadastrado alguma informação não fique o campo em branco. exemplo: 

- Cidade: 

Seria legal ter um campo como:

- Cidade: Você ainda não cadastrou a sua cidade

2024-01-26 18:21 UTC, GyodaiDDA approved these changes

2024-01-26 18:36 UTC, merged