Feat/comentarios curtidas
TreinaDev/td11-portfoliorrr pull request #39
Opened 2024-01-25 13:27 UTC by caiquedv

Essa pull request aborda e resolve #31 

Usuário pode comentar publicações:

- Cria model Comment para lidar com comentários de publicações. 
- Cria campo para comentários na tela de show da publicação.
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/101219858/24cd0e37-bf6f-4ea6-9bd7-f9dbd28826d6)

Usuário pode curtir uma publicação ou comentário:
- Cria model Like para lidar com curtidas em publicações e comentários:
- Adiciona botões para curtir
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/101219858/1a3f8044-25e6-4a5a-b87f-b3cdf381c88e)

Adiciona Testes de request garantindo que apenas usuários logado curtam ou comentem nas publicações ou comentários, redirecionando-os para login.
Aplica estilização com bootstrap na tela da publicação

2024-01-25 19:11 UTC, gabdemiranda reviewed
Parece tá tudo certinho, mas não entendi porque ficou em débito a validação para "um usuário não pode curtir mais de duas vezes a msm publicação se enviar outro post para a rota do like". Acredito que o model 'like' possa ter uma validação que não permita criar um objeto associado ao mesmo "likable" e usuário, senão ficaria um débito muito "solto" para agregar na app no futuro.

2024-01-25 22:42 UTC, hreis1 commented
> Parece tá tudo certinho, mas não entendi porque ficou em débito a validação para "um usuário não pode curtir mais de duas vezes a msm publicação se enviar outro post para a rota do like". Acredito que o model 'like' possa ter uma validação que não permita criar um objeto associado ao mesmo "likable" e usuário, senão ficaria um débito muito "solto" para agregar na app no futuro.

Beleza. É que só percebi depois que a PR foi feita e já estava em outro card, então deixei anotada essa vulnerabilidade. Vou fazer as alterações dessa parte antes do merge.

2024-01-26 13:40 UTC, DanSmaR requested changes
Parabéns pela nova feature, favor avaliar minhas considerações :)

2024-01-26 13:40 UTC, DanSmaR commented on spec/requests/comments/user_comments_post_spec.rb
> +  it 'não esta logado' do
@hreis1 e @gmkoeb, seria interessante deixar explicito na descrição do teste o que acontece se o usuário não está logado, como sem sucesso ou eh redirecionado para a página de login

2024-01-26 13:40 UTC, DanSmaR commented on spec/requests/likes/user_likes_spec.rb
> +    it 'e tenta curtir' do
Aqui mesma coisa, adicionar um sem sucesso ou é redirecionado

2024-01-26 13:40 UTC, DanSmaR commented on spec/system/comments/user_comments_blog_post_spec.rb
> +  it 'com mensagem em branco' do
acho que poderia ser sem sucesso com mensagem em branco

2024-01-26 13:40 UTC, DanSmaR commented on spec/system/likes/user_likes_spec.rb
> +        save_page
Esqueceu de retirar o save_page 😄

2024-01-26 14:22 UTC, hreis1 commented on spec/system/likes/user_likes_spec.rb
> +        save_page
ixe, blz vamos arrumar

2024-01-26 16:35 UTC, gmkoeb approved these changes
Ficou muito bom. Aprovei com alguns comentários. Achei bem legal ver o uso de polimorfismo, aprendi bastante!

2024-01-26 16:36 UTC, gmkoeb commented on app/views/posts/show.html.erb
> +          <%= comment.likes.count %> Curtida
Acho que ficou faltando colocar a tradução de curtida aqui, pra mudar pro plural de acordo com o count.

2024-01-26 17:14 UTC, DanSmaR commented on app/controllers/likes_controller.rb
> +      redirect_to post_path(post_id), notice: t('.success')
Vdd, tbm achei isso

2024-01-26 18:07 UTC, anaresgalla approved these changes
Só deixei comentários pq concordei com o Gabriel :))

2024-01-26 18:26 UTC, caiquedv commented on spec/requests/comments/user_comments_post_spec.rb
> +  it 'não esta logado' do
Boua! Feito!

2024-01-26 18:28 UTC, caiquedv commented on spec/system/comments/user_comments_blog_post_spec.rb
> +  it 'com mensagem em branco' do
Valeu, feito!

2024-01-26 19:05 UTC, DanSmaR approved these changes

2024-01-26 19:06 UTC, merged

2024-02-04 18:01 UTC, DanSmaR reviewed
Pessoal, segue um comentário sobre mantenibilidade de código usando Open Closed Principle do SOLID. Só para informação (FYI) e possível futura refatoração.
Seria um aprendizado legal para todos 😃

2024-02-04 18:01 UTC, DanSmaR commented on app/controllers/likes_controller.rb
> +end
Pessoal, estava vendo uns artigos e vídeos sobre associação polimórfica em Rails e aprendi algo legal. Vi que nós estamos usando dentro de cada action if statements para definir se se trata de um post ou comentário. Caso, no futuro, necessitássemos de inserir algo mais que possa ser curtido, teríamos de modificar o código, ferindo um dos princípios do SOLID, O => Open Closed Principle. Aberto para extensão, fechado para modificação.

E para não ferirmos esse princípio e tornar nosso código mais escalável e mantenível, podeŕiamos refatorar o código numa próxima oportunidade da seguinte maneira:

manteríamos esse controller base `LikesController`, com as actions `create` e as demais. Porém, criaríamos outros dois controllers, denominados: `Posts::LikesController < LikesController` e  `Comments::LikesController < LikesController`, onde setaríamos o tipo do likeable, sendo ou Comments ou Posts. Cada um desses controllers teria um método set_likeable, onde cada um retornaria o seu respectivo comentario ou post. E cada um desses controllers herdaria as actions do `LikesController`, eliminando a necessidade de if statements dentro das actions. E tornando nosso código mais mantenível e seguindo o Open Closed Principle do SOLID.

Para mais detalhes da implementação, favor me contatar.