Feat/Exibe perfil pesooal
TreinaDev/td11-portfoliorrr pull request #45
Opened 2024-01-26 22:35 UTC by caiquedv

Essa PR aborda e resolve #43.
Antes tinhamos uma página que exibia os dados do dono do perfil e uma tela de perfil sem as informações que só era acessível via pesquisa. Unificamos as duas telas para criar um perfil. 

- [x] Adiciona link para o perfil na navbar
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/101219858/77f62550-a3a2-4b11-a54b-c5dffb3e58ab)

- [x] Exibe dados de todos os usuários em seu respectivo perfil
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/101219858/b8dfd70c-1059-4df5-899f-51451acef316)

- [x] Somente o dono pode editar as informações do perfil
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/101219858/981eb3ff-951d-400d-809d-fc9403537732)
![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/101219858/a2f897ce-2456-41ae-a818-d791095a715b)

- [x] Refatora rotas dos testes relacionados ao perfil antigo

2024-01-27 14:39 UTC, eliseuramos93 requested changes
Galera, gostei bastante de como ficou a aparência da aplicação. Fiz um comentário sobre mostrar informações que não foram preenchidas como perfil, mas deixo aquele ponto mais como sugestão do que uma alteração necessária.

Ao navegar na app, encontrei alguns pequenos bugs na navegação como botões "Voltar" que não executam ações em cenários específicos, por isso solicitei alterações para corrigirmos os comportamentos desses botões para que eles redirecionem para uma página que entendemos como a "correta" na jornada do cliente, mesmo que ele tenha vindo de uma outra rota qualquer.

Além disso, o Rspec não está mais passando por causa de um bug que vocês acabaram herdando de uma PR anterior que já teve merge na main, e acabou passando batido.

Estou rodando o teste no dia 27 de janeiro, mas a data de edição da publicação está sendo jogada para um valor aprox. 18h antes do momento que o teste é rodado.

Isso tá acontecendo porque o atributo edited_at não foi configurado na factory do Post, e isso por algum motivo está travando o atributo no passado conforme imagem abaixo:

![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/111306649/dde04079-5637-40e0-82ca-48b6c0c8e7b5)

2024-01-27 14:39 UTC, eliseuramos93 commented on spec/system/personal_info/user_edits_personal_info_spec.rb
>        user_name = personal_info.profile.user.description
Na alteração vocês criaram o usuário, talvez já poderiam ter aproveitado e usado `user_name = user.description` aqui.

2024-01-27 14:39 UTC, eliseuramos93 commented on app/views/profile_job_categories/new.html.erb
> +    <%= link_to t('buttons.return'), request.referer || root_path, class: 'btn btn-secondary' %>
Essa alteração adiciona um bug à página.

Se o usuário preenche o formulário errado, tenta salvar e depois clica em Voltar, o botão entra num loop infinito de redirecionamento apenas para o formulário. O ideal seria um redirecionamento mesmo para o perfil do usuário.

Também não entendi porque a opção entre voltar para última página, ou a raiz. Fiquei confuso com essa decisão.

2024-01-27 14:39 UTC, eliseuramos93 commented on app/controllers/profile_job_categories_controller.rb
> +                notice: t('.check_if_job_categories_exist.error')
Achei interessante essa lógica, gostei e vou aderir a essa prática tbm.

2024-01-27 16:47 UTC, DanSmaR commented on app/views/profile/_profile.html.erb
> +    </li>
Boa, somente o dono do perfil vê os campos em branco agora, para lembrá-lo de preenchê-los.
Valeu :)

2024-01-27 16:55 UTC, DanSmaR commented on spec/system/personal_info/user_edits_personal_info_spec.rb
>        user_name = personal_info.profile.user.description
Boa

2024-01-28 11:42 UTC, eliseuramos93 approved these changes
Parabéns pessoal, gostei bastante das mudanças que vocês incluíram na app! 

Já vou deixar com aprovação, porque entendo que os pontos que levantei não são bugs ou coisas que precisam ser arrumadas neste momento, e sim pequenas alterações que podem ser feitas num commit rápido ou colocadas como débito para uma futura PR. 

Minha sugestão é de apenas alterar o método booleano que não terminou em `?`, os demais pontos descrever na PR como débitos futuros para outra issue, e realizar o merge na main.

2024-01-29 11:44 UTC, decoporteira approved these changes
A tela ficou ótima, só ela já mudou toda a cara do projeto.
Vou só deixar um feedback: Nas experiências profissionais e na formação acadêmica você pode colocar a data final menor que a data de início, não acho que seja um problema, pois não usaremos essas datas em nada por enquanto, mas acho que cabe colocar isso nas futuras melhorias.
Vou aprovar pois acho que isso não compromete o trabalho feito.

2024-01-29 13:07 UTC, gabdemiranda commented on app/views/profile/_profile.html.erb
> +  <% if current_user == profile.user%>
Acredito que essa lógica para verificar se o usuário é o current user para setar os atributos corretamente poderia ficar no controller

2024-01-29 13:14 UTC, gabdemiranda commented on spec/system/profile/user_views_profile_spec.rb
> +      visit profile_path(1)
Não deveria existir pelo menos esse perfil que tivesse esse "id 1" ou passasse ele na rota, no setup do teste, para garantir que não é um falso positivo?

2024-01-29 13:23 UTC, gabdemiranda reviewed
Acho que poderiam ser adicionados testes para garantir que os títulos das informações adicionais aparecem ou não, além de expectativas do comportamento desses campos que também ficam na tela de perfil e podem ou não aparecer

2024-01-29 13:25 UTC, DanSmaR commented on app/models/personal_info.rb
> +  end
Bem observado ! Alterado :)

2024-01-29 14:27 UTC, DanSmaR commented on app/views/profile/_profile.html.erb
> +  <% if current_user == profile.user%>
Show :), fizemos isso! Valeu

2024-01-29 14:29 UTC, DanSmaR commented on spec/system/profile/user_views_profile_spec.rb
> +      visit profile_path(1)
vdd, não tínhamos percebido isso, valeu :)

2024-01-29 14:37 UTC, DanSmaR commented on spec/system/profiles/user_views_other_user_profile_spec.rb
> +  it 'e não consegue editar perfil de outro usuário' do
Boa, mudamos o nome do teste para verificar se tem links.
A parte do current_path fizemos um teste de request específico para cada formulário de edição

2024-01-29 14:48 UTC, merged