Usuário muda status da publicação
TreinaDev/td11-portfoliorrr pull request #57
Opened 2024-01-30 15:58 UTC by hreis1

resolve #55 

- Foi adicionado status de Publicada, Arquivada e Rascunho paras as publicações.
- Publicações arquivadas e rascunhadas são vistas somente pelo próprio autor

Usuário dono visualiza publicação arquivada
![Captura de tela 2024-01-30 125348](https://github.com/TreinaDev/td11-portfoliorrr/assets/94029691/7323d567-cf4d-4d2d-bc69-49e79c2be6eb)

Usuário dono pode editar status da publicação
![Captura de tela 2024-01-30 125354](https://github.com/TreinaDev/td11-portfoliorrr/assets/94029691/0cacffb0-04c8-4577-9032-e307431f75a8)

2024-01-31 17:27 UTC, DanSmaR approved these changes
Muito bom! Vamo que vamo :)

2024-01-31 18:24 UTC, GyodaiDDA requested changes

2024-01-31 18:24 UTC, GyodaiDDA commented on spec/system/home/user_views_home_page_spec.rb
>        gabriel.posts.create(title: 'Como fazer uma app Vue', content: 'Não esqueça de usar o app.mount')
Não entendi porque não tem status na criação. Qual o status padrão?

2024-01-31 18:30 UTC, hreis1 commented on spec/system/home/user_views_home_page_spec.rb
>        gabriel.posts.create(title: 'Como fazer uma app Vue', content: 'Não esqueça de usar o app.mount')
Na criação de qualquer post o status padrão é 'publicado'. Tem um teste unitário para isso no spec/models/post_spec.rb:58

2024-02-01 14:14 UTC, GyodaiDDA commented on spec/system/home/user_views_home_page_spec.rb
>        gabriel.posts.create(title: 'Como fazer uma app Vue', content: 'Não esqueça de usar o app.mount')
Então a gente deveria esperar que essa postagem criada sem status, fosse visível, mas ali na linha 25, tem um 'expect not_to' do link dessa postagem.

2024-02-01 21:33 UTC, GyodaiDDA approved these changes

2024-02-02 12:38 UTC, gabdemiranda approved these changes

2024-02-02 13:21 UTC, merged