Mostra usuários mais seguidos na home
TreinaDev/td11-portfoliorrr pull request #68
Opened 2024-01-30 21:12 UTC by hreis1

resolve #61 

cria listagem na home de 3 perfis mais seguidos

![image](https://github.com/TreinaDev/td11-portfoliorrr/assets/94029691/2d0cedf0-0a8a-4548-be65-dbbf4eeb59d1)

2024-01-31 17:38 UTC, gmkoeb reviewed
Muito bacana, ficou bem legal a home com a tabela de usuários mais seguidos.

2024-01-31 17:38 UTC, gmkoeb commented on spec/system/home/user_views_home_page_spec.rb
>    context 'quando não está logado' do
Talvez seria uma boa incluir um teste que o usuário deslogado não vê a tabela de usuários mais seguidos

2024-01-31 18:14 UTC, anaresgalla commented on spec/system/home/user_views_home_page_spec.rb
>    context 'quando não está logado' do
a única sugestão que eu dou é esse teste para visitante/usuário não logado não ver os mais seguidos
Tá mto bom! Gostei bastante, meninos! :))

2024-01-31 18:15 UTC, anaresgalla approved these changes
a única sugestão que eu dou é esse teste para visitante/usuário não logado não ver os mais seguidos
Tá mto bom! Gostei bastante, meninos! :))

2024-01-31 18:15 UTC, anaresgalla commented on spec/system/home/user_views_home_page_spec.rb
>    context 'quando não está logado' do
a única sugestão que eu dou é esse teste para visitante/usuário não logado não ver os mais seguidos
Tá mto bom! Gostei bastante, meninos! :))

2024-02-01 14:27 UTC, eliseuramos93 requested changes
Pessoal, bom trabalho aqui! 

Faltou apenas um teste para validar que o usuário não logado é incapaz de ver a tabela de usuários mais seguidos. Com essa alteração, fica 100% pra subir na main.

2024-02-01 14:27 UTC, eliseuramos93 commented on spec/system/home/user_views_home_page_spec.rb
>    context 'quando não está logado' do
Concordo com esse ponto. Como a lógica implementa isso, acredito que isso precisa ser testado.

2024-02-01 17:30 UTC, eliseuramos93 approved these changes
Tudo certo!

2024-02-01 17:31 UTC, merged