Feat/foto de perfil
TreinaDev/td11-portfoliorrr pull request #80
Opened 2024-01-31 14:59 UTC by eliseuramos93

2024-02-02 20:10 UTC, akaninja commented
Os testes passaram! Amém

2024-02-03 00:16 UTC, gmkoeb approved these changes
Muito bom, não encontrei nenhuma ponta solta. A aplicação vai ficar bem bacana com as fotos de perfil 🙌

2024-02-03 14:28 UTC, hreis1 commented on config/locales/profile.pt-BR.yml
> +      unauthorized_user: 'Você não possui autorização para essa ação'
Em config/locales/alerts.pt-BR.yml, há uma mensagem de unauthorized. Pode ser interessante pegar essa mensagem de lá para padronização e facilidade de alteração geral.

2024-02-03 14:31 UTC, hreis1 commented on app/models/profile.rb
> +    return if photo.byte_size <= 3 * 1024 * 1024
da pra fazer
`
3.megabytes
`

2024-02-03 14:45 UTC, hreis1 commented on spec/resources/photos/jennifer-lawrence.jpg
como esse arquivo é usado para o teste de: 'foto deve ser menor que 3MB' pode ser interessante deixar isso explicito no nome dela

2024-02-03 14:52 UTC, hreis1 requested changes
Na pasta principal, há o diretório spec/support/assets/, onde estão todos os arquivos usados nos testes. Acredito que mover os arquvios de spec/resources para lá antes de fazer o merge pode ser uma boa ideia

2024-02-03 14:53 UTC, hreis1 approved these changes

2024-02-03 14:56 UTC, hreis1 commented
Deixei aprovado, acho que na hora de resolver os conflitos já dá para mover os arquivos. Ficou muito bom essa funcionalidade, vai dar um boom no nosso app. Parabéns!

2024-02-03 16:18 UTC, DanSmaR approved these changes
Ficou muito legal Time EliAna 💯

2024-02-03 16:18 UTC, DanSmaR commented on spec/system/profile_photo/profile_shows_user_photo_spec.rb
> +      save_screenshot
Acho q esqueceu de retirar esse save_screenshot

2024-02-05 12:35 UTC, eliseuramos93 commented on config/locales/profile.pt-BR.yml
> +      unauthorized_user: 'Você não possui autorização para essa ação'
Boa PH, já ajustamos lá pra usar o alerta dessa página. vlw!

2024-02-05 12:35 UTC, eliseuramos93 commented on app/models/profile.rb
> +    return if photo.byte_size <= 3 * 1024 * 1024
Daora mano, não sabia desse método! Vlw!

2024-02-05 12:35 UTC, eliseuramos93 commented on spec/resources/photos/jennifer-lawrence.jpg
Muito bem pensado, já ajustamos isso tbm!

2024-02-05 12:35 UTC, eliseuramos93 commented on spec/system/profile_photo/profile_shows_user_photo_spec.rb
> +      save_screenshot
Boa Dan, passou batido mesmo! Já subimos um commit para remover

2024-02-05 12:37 UTC, merged